export const seedExerciseNames = {
  es: {
    benchPress: 'Press de banca', inclinePress: 'Press inclinado', chestFly: 'Aperturas',
    dips: 'Fondos', latPulldown: 'Jalón al pecho', barbellRow: 'Remo con barra',
    deadlift: 'Peso muerto', facePull: 'Face Pull', squat: 'Sentadilla', legPress: 'Prensa',
    legExtension: 'Extensiones', legCurl: 'Curl femoral', romanianDeadlift: 'Peso muerto rumano',
    goodMorning: 'Buenos días', hipThrust: 'Hip Thrust', bulgarianSplitSquat: 'Sentadilla búlgara',
    gluteKickback: 'Patada de glúteo', militaryPress: 'Press militar',
    lateralRaise: 'Elevaciones laterales', frontRaise: 'Elevaciones frontales',
    barbellCurl: 'Curl con barra', hammerCurl: 'Curl martillo', inclineCurl: 'Curl inclinado',
    skullCrusher: 'Press francés', tricepPushdown: 'Extensiones de tríceps',
    tricepKickback: 'Patada de tríceps', crunch: 'Crunch', plank: 'Plancha',
    legRaise: 'Elevación de piernas', treadmill: 'Cinta', bike: 'Bicicleta',
    elliptical: 'Elíptica', cableWristCurl: 'Antebrazo en polea', shrugs: 'Encogimientos de hombros',
  },
  en: {
    benchPress: 'Bench Press', inclinePress: 'Incline Press', chestFly: 'Chest Fly', dips: 'Dips',
    latPulldown: 'Lat Pulldown', barbellRow: 'Barbell Row', deadlift: 'Deadlift', facePull: 'Face Pull',
    squat: 'Squat', legPress: 'Leg Press', legExtension: 'Leg Extension', legCurl: 'Leg Curl',
    romanianDeadlift: 'Romanian Deadlift', goodMorning: 'Good Morning', hipThrust: 'Hip Thrust',
    bulgarianSplitSquat: 'Bulgarian Split Squat', gluteKickback: 'Glute Kickback',
    militaryPress: 'Military Press', lateralRaise: 'Lateral Raise', frontRaise: 'Front Raise',
    barbellCurl: 'Barbell Curl', hammerCurl: 'Hammer Curl', inclineCurl: 'Incline Curl',
    skullCrusher: 'Skull Crusher', tricepPushdown: 'Tricep Pushdown',
    tricepKickback: 'Tricep Kickback', crunch: 'Crunch', plank: 'Plank', legRaise: 'Leg Raise',
    treadmill: 'Treadmill', bike: 'Bike', elliptical: 'Elliptical',
    cableWristCurl: 'Cable Wrist Curl', shrugs: 'Shrugs',
  },
} as const;
